
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Apr 05 08:02:01 BRT 2009
//----------------------------------------------------

package satlfiinconsdef;

/** CUP generated class containing symbol constants. */
public class satlfiinconsdefsym {
  /* terminals */
  public static final int AND = 3;
  public static final int XOR = 5;
  public static final int SIGN = 16;
  public static final int CONSISTENCY = 13;
  public static final int EOL = 10;
  public static final int TOP = 11;
  public static final int STRING = 15;
  public static final int EOF = 0;
  public static final int INCONSISTENCY = 14;
  public static final int error = 1;
  public static final int BOTTOM = 12;
  public static final int RPAREN = 9;
  public static final int IMPLIES = 7;
  public static final int NEG = 2;
  public static final int LPAREN = 8;
  public static final int OR = 4;
  public static final int BIIMPLIES = 6;
}

