
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Apr 05 08:01:45 BRT 2009
//----------------------------------------------------

package ConversorWagnerSATLIB;

/** CUP generated class containing symbol constants. */
public class ConversorWagnerSATLIBsym {
  /* terminals */
  public static final int AND = 5;
  public static final int XOR = 7;
  public static final int SIGN = 2;
  public static final int CONSISTENCY = 14;
  public static final int EOL = 3;
  public static final int TRUE = 12;
  public static final int EOF = 0;
  public static final int FALSE = 13;
  public static final int ID = 16;
  public static final int INCONSISTENCY = 15;
  public static final int error = 1;
  public static final int RPAREN = 11;
  public static final int IMPLIES = 8;
  public static final int NEG = 4;
  public static final int LPAREN = 10;
  public static final int OR = 6;
  public static final int BIIMPLIES = 9;
}

